# Generated by Django 3.2.16 on 2025-12-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('undefined', 'Неизвестно'), ('on_display', 'На экспозиции'), ('in_storage', 'На складе'), ('on_restoration', 'На реставрации'), ('on_loan', 'В аренде'), ('removed', 'Списан')], default='undefined', max_length=50)),
                ('last_movement_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('added', 'Добавлен в фонд'), ('moved_to_hall', 'Перемещён в зал'), ('sent_to_restoration', 'Отправлен на реставрацию'), ('returned_from_restoration', 'Возвращён из реставрации'), ('sent_to_storage', 'Отправлен на склад'), ('sent_on_loan', 'Отдан в аренду'), ('returned_from_loan', 'Возвращён из аренды'), ('removed', 'Списан')], max_length=50)),
                ('from_location', models.CharField(blank=True, max_length=100)),
                ('to_location', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='exhibits.exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='exhibits.floor')),
            ],
        ),
        migrations.CreateModel(
            name='ExhibitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibits/')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibits.exhibit')),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='hall',
            field=models.ForeignKey(blank=True, help_text="Только если статус — 'На экспозиции'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='exhibits.hall'),
        ),
    ]
